spring:
  application:
    name: acquisitions-tools
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

folio:
  api:
    url: ${FOLIO_URL}
    tenant: ${FOLIO_TENANT}
    username: ${FOLIO_USERNAME}
    password: ${FOLIO_PASSWORD}
